// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;

public class AI : Player
{
	public AI (string name) :base(name)
	{
	}

	override public void move()
	{
		
		this.endPlayersTurn ();
		
	}

	override public void setupUnits(Map map, Hex hex)
	{
	}

	override public void setupUnits(Map map){}

	override public void removeUnit(Unit unit){}
}


