// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using UnityEngine;

	public class Animal : Unit
	{
		public string name = "naming things";
		public Animal ()
		{
			this.unit_marker = GameObject.CreatePrimitive(PrimitiveType.Cube);
			this.unit_marker.transform.position = new Vector3(-1000,-1000,0);
			this.unit_marker.GetComponent<Renderer>().material.color = ColorGenerator.getColorFromString ("grass");
			
		}
		
		public Animal (Vector3 vector)
		{
			this.name = "naimg";
			this.unit_marker = GameObject.CreatePrimitive(PrimitiveType.Cube);
			this.unit_marker.transform.position = vector;
			this.vector = vector;
			this.unit_marker.GetComponent<Renderer>().material.color = ColorGenerator.getColorFromString ("grass");
			
			Vector2 hex_coordinates = GameUtils.getHexMapCoordinatesFromPoint (GameEngine.map, 	new Vector3(vector.x, vector.y + 1.0f, vector.z), GameEngine.num_row, GameEngine.num_col);
			Hex hexAtPoint = GameUtils.getHexFromPoint (vector, GameEngine.map, GameEngine.num_row, GameEngine.num_col);
			this.hex_coordinates_x = Mathf.RoundToInt(hex_coordinates.x);
			this.hex_coordinates_y = Mathf.RoundToInt(hex_coordinates.y);
			this.vector = vector;
			
			GameEngine.map.terrain [hex_coordinates_x, hex_coordinates_y].setUnit (this);
			
			this.on_hex = GameEngine.map.terrain [this.hex_coordinates_x, this.hex_coordinates_y];
//			GameUtils.destroyCollider (this.unit_marker);

		}
		
		public void move(Vector3 vector)
		{
			GameEngine.map.terrain [this.hex_coordinates_x, this.hex_coordinates_y].unit = null;
			this.unit_marker.transform.position = vector;
			Vector2 hex_coordinates = GameUtils.getHexMapCoordinatesFromPoint (GameEngine.map, vector, GameEngine.num_row, GameEngine.num_col);
			Debug.Log ("hex coords received" + hex_coordinates);
			this.hex_coordinates_x = Mathf.RoundToInt(hex_coordinates.x);
			this.hex_coordinates_y = Mathf.RoundToInt(hex_coordinates.y);
			GameEngine.map.terrain [this.hex_coordinates_x, this.hex_coordinates_y].setUnit (this);
			
			
		}
		
		public void move(Vector3 vector, Hex hex)
		{
			on_hex.unit = null;
			unit_marker.transform.position = vector;
			this.on_hex = hex;
			hex.unit = this;
		}
		
		public void move(Hex hex){
			Debug.Log("on hex: " + on_hex.pos + " moving to hex: " + hex.pos);
			this.unit_marker.transform.position = hex.center;
			this.on_hex.unit = null;
			this.on_hex = hex;
			hex.unit = this;
		}
		
		public void move() {
			int r = Random.Range (0, 6);
			Vector2 position = on_hex.pos;
			int x = (int)position.x;
			int y = (int)position.y;
			Debug.Log (position);
			switch (r) {
				case 0:
					if(x+1 >= GameEngine.num_row){
						this.move ();
						break;
					}
					move (GameEngine.map.terrain[x+1, y]);
					break;
				case 1:
					if(y+1 >= GameEngine.num_col){
						this.move ();
						break;
					}
					move (GameEngine.map.terrain[x, y+1]);
					break;
				case 2:
					if(x-1 <= 0 || y+1 >= GameEngine.num_col){
						this.move ();
						break;
					}
					move (GameEngine.map.terrain[x-1,y+1]);
					break;
				case 3:
					if(x-1 <= 0){
						this.move ();
						break;
					}
					move (GameEngine.map.terrain[x-1,y]);
					break;
				case 4:
					if(x-1 <= 0 || y-1 <= 0){
						this.move ();
						break;
					}
					move (GameEngine.map.terrain[x-1, y-1]);
					break;
				case 5:
					if(y-1 <= 0){
						this.move ();
						break;
					}
					move (GameEngine.map.terrain[x, y-1]);
					break;
				case 6:
					break;
			}
		}

		public string toString()
		{
			return "Animal on: " + this.hex_coordinates_x + " " + this.hex_coordinates_y + " with vector: " + this.vector;
		}

	}

