// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;

public class Human : Player
{

	public Human (string name) : base(name)
	{
		this.available = 1;
	}

	override public void move()
	{

		while(this.is_players_turn)
		{

		}

	}

	override public void setupUnits(Map map, Hex hex)
	{
		this.units = new Unit[1];
		Unit new_unit = new Unit (hex);
		this.units [0] = new_unit;
		hex.setUnit((Unit)this.units [0]);
		available--;
		unit_counter++;
		this.units [0].id = unit_counter;
		this.units [0].player = this;
	}

	override public void setupUnits(Map map){

	}

	override public void removeUnit(Unit unit){
		this.units = new Unit[0];
		available++;
	}

}














































