// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;

public class Human : Player
{

	public Human (string name) : base(name)
	{


	}

	override public void move()
	{

		while(this.is_players_turn)
		{

		}

	}

	override public void setupUnits(Map map, Vector2 vector)
	{
		this.units = new Unit[1];
		Unit new_unit = new Unit (map.terrain[(int)vector.x, (int)vector.y].center);
		this.units [0] = new_unit;
		map.terrain[(int)vector.x, (int)vector.y].setUnit((Unit)this.units [0]);
	}
	override public void setupUnits(Map map){

	}

}














































