// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class Nature : Player
{
	private int total_units;
	public static List<Animal> animals  = new List<Animal>();


	public Nature (string name) : base(name)
	{
	}

//	override public void setupUnits(Map map, Vector2 vector)
//	{
//		this.units = new Unit[1];
//		Unit new_unit = new Unit (map.terrain[(int)vector.x, (int)vector.y].center);
//		this.units [0] = new_unit;
//		map.terrain[(int)vector.x, (int)vector.y].setUnit((Unit)this.units [0]);
//	}

	override public void move()
	{
		Debug.Log ("inside move");
//		setupUnits (GameEngine.map);
		foreach (Animal ani in animals) {
			ani.move();
		}
//				if(animals[i]!=null){
//					Debug.Log ("units at i are not null");
//				}
//				Debug.Log ("units at i are null");
//				animals.IndexOf(i).move();
//				animals.FindIndex(i).move();
//				units[i].move (GameEngine.map.terrain[6,15]);
	}

	override public void setupUnits(Map map, Vector2 vector)
	{
	}


	override public void setupUnits(Map map){
		total_units = (int)( GameEngine.num_col * GameEngine.num_row * 0.15);
		for (int i=0; i< total_units; i++) {
			//get random hex.ps
			Hex temp = map.terrain[Random.Range (0,GameEngine.num_row), Random.Range (0, GameEngine.num_col)];
			if(GameUtils.isLand(temp)){
				Vector3 position = temp.center;
				Animal newAnimal = new Animal(position);
				newAnimal.on_hex = temp;
				animals.Add ( newAnimal );
				temp.setUnit(newAnimal);
			}
		}
	}

}