// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;

public class Nature
{
	private int total_units = (int)( GameEngine.num_col * GameEngine.num_row * 0.15);

	public Nature ()
	{
		for(int i=0; i<total_units; i++){
			Debug.Log("nothing");
		}
	}
}